package report

import (
	"fmt"
	"io"
	"strings"
)

func renderMarkdown(r *Report, w io.Writer) error {
	if _, err := fmt.Fprintf(w,
		"# hardbox Audit Report\n\n"+
			"| Field | Value |\n|---|---|\n"+
			"| Session | `%s` |\n"+
			"| Profile | `%s` |\n"+
			"| Timestamp | %s |\n"+
			"| **Overall Score** | **%d%%** |\n\n",
		r.SessionID,
		r.Profile,
		r.Timestamp.Format("2006-01-02 15:04:05 UTC"),
		r.OverallScore,
	); err != nil {
		return err
	}

	for _, mod := range r.Modules {
		if _, err := fmt.Fprintf(w,
			"## Module: `%s`  —  Score: %d%%\n\n"+
				"| Check ID | Status | Severity | Title | Detail |\n"+
				"|---|---|---|---|---|\n",
			mod.Name, mod.Score,
		); err != nil {
			return err
		}

		for _, f := range mod.Findings {
			detail := strings.ReplaceAll(f.Detail, "|", "\\|")
			title := strings.ReplaceAll(f.Title, "|", "\\|")
			if _, err := fmt.Fprintf(w, "| `%s` | %s | %s | %s | %s |\n",
				f.CheckID,
				mdStatusBadge(f.Status),
				f.Severity,
				title,
				detail,
			); err != nil {
				return err
			}
		}

		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}

	compliant, total := countFindings(r)
	_, err := fmt.Fprintf(w,
		"---\n\n*%d compliant / %d total findings — generated by hardbox*\n",
		compliant, total,
	)
	return err
}

func mdStatusBadge(status string) string {
	switch status {
	case "compliant":
		return "✅ compliant"
	case "non-compliant":
		return "❌ non-compliant"
	case "manual":
		return "⚠️ manual"
	case "skipped":
		return "⏭️ skipped"
	default:
		return "🚨 " + status
	}
}
