// Copyright (C) 2024 Jack (jackby03)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
// Package kernel implements sysctl-based kernel hardening checks.
// It covers network protection (kn-001..011) and memory/process protection
// (km-001..008) derived from CIS Benchmark Level 1.
package kernel

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hardbox-io/hardbox/internal/modules"
	"github.com/hardbox-io/hardbox/internal/modules/util"
)

const (
	sysctlConfPath = "/etc/sysctl.d/99-hardbox.conf"
	procSysBase    = "/proc/sys"
)

// Module implements kernel sysctl hardening.
type Module struct {
	// procBase allows tests to inject a fake /proc/sys root.
	procBase string
}

func (m *Module) Name() string    { return "kernel" }
func (m *Module) Version() string { return "1.0" }

func (m *Module) base() string {
	if m.procBase != "" {
		return m.procBase
	}
	return procSysBase
}

// Audit reads current sysctl values from /proc/sys and compares them against
// the hardened expected values. It is read-only and has no side effects.
func (m *Module) Audit(_ context.Context, _ modules.ModuleConfig) ([]modules.Finding, error) {
	checks := allChecks()
	findings := make([]modules.Finding, 0, len(checks))

	for _, chk := range checks {
		current, err := m.readSysctl(chk.param)
		if err != nil {
			if os.IsNotExist(err) {
				// Param not present in this kernel — report as skipped.
				findings = append(findings, modules.Finding{
					Check:  chk.check,
					Status: modules.StatusSkipped,
					Detail: fmt.Sprintf("sysctl param %q not available: %v", chk.param, err),
				})
				continue
			}
			// Unexpected error reading the sysctl — report as error.
			findings = append(findings, modules.Finding{
				Check:  chk.check,
				Status: modules.StatusError,
				Detail: fmt.Sprintf("failed to read sysctl param %q: %v", chk.param, err),
			})
			continue
		}

		status := modules.StatusCompliant
		if !chk.validate(current) {
			status = modules.StatusNonCompliant
		}

		findings = append(findings, modules.Finding{
			Check:   chk.check,
			Status:  status,
			Current: current,
			Target:  chk.expected,
			Detail:  fmt.Sprintf("current: %q, expected: %q", current, chk.expected),
		})
	}

	return findings, nil
}

// Plan builds a single atomic Change that writes /etc/sysctl.d/99-hardbox.conf
// with the required hardened values for all non-compliant parameters — one file, one revert.
func (m *Module) Plan(ctx context.Context, _ modules.ModuleConfig) ([]modules.Change, error) {
	findings, err := m.Audit(ctx, nil)
	if err != nil {
		return nil, err
	}

	// Collect non-compliant params only.
	checks := allChecks()
	type fix struct {
		param, expected string
	}
	var fixes []fix
	for i, f := range findings {
		if i >= len(checks) {
			continue
		}
		if !f.IsCompliant() && f.Status != modules.StatusSkipped {
			fixes = append(fixes, fix{
				param:    checks[i].param,
				expected: f.Target,
			})
		}
	}

	if len(fixes) == 0 {
		return nil, nil
	}

	// Build the new sysctl.d config content.
	var sb strings.Builder
	sb.WriteString("# Generated by hardbox — do not edit manually\n")
	for _, f := range fixes {
		fmt.Fprintf(&sb, "%s = %s\n", f.param, f.expected)
	}
	newContent := []byte(sb.String())

	// Read existing file for revert; distinguish missing file from real I/O errors.
	oldContent, readErr := os.ReadFile(sysctlConfPath)
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, fmt.Errorf("kernel: read existing %s: %w", sysctlConfPath, readErr)
	}
	fileExisted := readErr == nil

	return []modules.Change{
		{
			Description:  fmt.Sprintf("kernel: write %d hardened sysctl parameters to %s", len(fixes), sysctlConfPath),
			DryRunOutput: sb.String(),
			Apply: func() error {
				return util.AtomicWrite(sysctlConfPath, newContent, 0o644)
			},
			Revert: func() error {
				if !fileExisted {
					return os.Remove(sysctlConfPath)
				}
				return util.AtomicWrite(sysctlConfPath, oldContent, 0o644)
			},
		},
	}, nil
}

// readSysctl reads the current value of a sysctl parameter from /proc/sys.
// The parameter uses dot notation (e.g. "net.ipv4.ip_forward"); dots are
// converted to path separators to locate the file.
func (m *Module) readSysctl(param string) (string, error) {
	relPath := strings.ReplaceAll(param, ".", string(filepath.Separator))
	path := filepath.Join(m.base(), relPath)
	// Reject path traversal by ensuring the final path is contained within the base.
	cleanBase := filepath.Clean(m.base())
	cleanPath := filepath.Clean(path)
	rel, err := filepath.Rel(cleanBase, cleanPath)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
		return "", fmt.Errorf("invalid sysctl path: %q", param)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

