// Package kernel implements sysctl-based kernel hardening checks.
// It covers network protection (kn-001..011) and memory/process protection
// (km-001..008) derived from CIS Benchmark Level 1.
package kernel

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hardbox-io/hardbox/internal/modules"
)

const (
	sysctlConfPath = "/etc/sysctl.d/99-hardbox.conf"
	procSysBase    = "/proc/sys"
)

// Module implements kernel sysctl hardening.
type Module struct {
	// procBase allows tests to inject a fake /proc/sys root.
	procBase string
}

func (m *Module) Name() string    { return "kernel" }
func (m *Module) Version() string { return "1.0" }

func (m *Module) base() string {
	if m.procBase != "" {
		return m.procBase
	}
	return procSysBase
}

// Audit reads current sysctl values from /proc/sys and compares them against
// the hardened expected values. It is read-only and has no side effects.
func (m *Module) Audit(_ context.Context, _ modules.ModuleConfig) ([]modules.Finding, error) {
	checks := allChecks()
	findings := make([]modules.Finding, 0, len(checks))

	for _, chk := range checks {
		current, err := m.readSysctl(chk.param)
		if err != nil {
			// Param not present in this kernel — report as skipped.
			findings = append(findings, modules.Finding{
				Check:  chk.check,
				Status: modules.StatusSkipped,
				Detail: fmt.Sprintf("sysctl param %q not available: %v", chk.param, err),
			})
			continue
		}

		status := modules.StatusCompliant
		if !chk.validate(current) {
			status = modules.StatusNonCompliant
		}

		findings = append(findings, modules.Finding{
			Check:   chk.check,
			Status:  status,
			Current: current,
			Target:  chk.expected,
			Detail:  fmt.Sprintf("current: %q, expected: %q", current, chk.expected),
		})
	}

	return findings, nil
}

// Plan builds a single atomic Change that writes /etc/sysctl.d/99-hardbox.conf
// with all required hardened values — one file, one revert.
func (m *Module) Plan(ctx context.Context, _ modules.ModuleConfig) ([]modules.Change, error) {
	findings, err := m.Audit(ctx, nil)
	if err != nil {
		return nil, err
	}

	// Collect non-compliant params only.
	type fix struct {
		param, expected string
	}
	var fixes []fix
	for i, f := range findings {
		if !f.IsCompliant() && f.Status != modules.StatusSkipped {
			fixes = append(fixes, fix{
				param:    allChecks()[i].param,
				expected: f.Target,
			})
		}
	}

	if len(fixes) == 0 {
		return nil, nil
	}

	// Build the new sysctl.d config content.
	var sb strings.Builder
	sb.WriteString("# Generated by hardbox — do not edit manually\n")
	for _, f := range fixes {
		fmt.Fprintf(&sb, "%s = %s\n", f.param, f.expected)
	}
	newContent := []byte(sb.String())

	// Read existing file for revert (may not exist yet).
	oldContent, _ := os.ReadFile(sysctlConfPath)

	return []modules.Change{
		{
			Description:  fmt.Sprintf("kernel: write %d hardened sysctl parameters to %s", len(fixes), sysctlConfPath),
			DryRunOutput: sb.String(),
			Apply: func() error {
				return atomicWrite(sysctlConfPath, newContent, 0o644)
			},
			Revert: func() error {
				if len(oldContent) == 0 {
					return os.Remove(sysctlConfPath)
				}
				return atomicWrite(sysctlConfPath, oldContent, 0o644)
			},
		},
	}, nil
}

// readSysctl reads the current value of a sysctl parameter from /proc/sys.
// The parameter uses dot notation (e.g. "net.ipv4.ip_forward"); dots are
// converted to path separators to locate the file.
func (m *Module) readSysctl(param string) (string, error) {
	relPath := strings.ReplaceAll(param, ".", string(filepath.Separator))
	path := filepath.Join(m.base(), relPath)
	// Reject path traversal
	if !strings.HasPrefix(filepath.Clean(path), filepath.Clean(m.base())) {
		return "", fmt.Errorf("invalid sysctl path: %q", param)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

// atomicWrite writes data to path using a temp-file + rename so the target
// is never left in a partial state.
func atomicWrite(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("atomicWrite mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".hardbox-tmp-")
	if err != nil {
		return fmt.Errorf("atomicWrite create temp: %w", err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("atomicWrite write: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("atomicWrite close: %w", err)
	}
	if err := os.Chmod(tmpName, mode); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("atomicWrite chmod: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("atomicWrite rename: %w", err)
	}
	return nil
}
