// Copyright (C) 2024 Jack (jackby03)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
package network

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hardbox-io/hardbox/internal/modules"
	"github.com/hardbox-io/hardbox/internal/modules/util"
)

const (
	defaultIPv6DisablePath = "/proc/sys/net/ipv6/conf/all/disable_ipv6"
	defaultModprobeDir     = "/etc/modprobe.d"
	defaultHostsAllowPath  = "/etc/hosts.allow"
	defaultHostsDenyPath   = "/etc/hosts.deny"
	defaultWirelessPath    = "/proc/net/wireless"
	defaultPasswdPath      = "/etc/passwd"
	blacklistFileName      = "hardbox-disable.conf"
)

type moduleCheck struct {
	id          string
	title       string
	severity    modules.Severity
	cisRef      string
	moduleName  string
	configKey   string
	defaultBool bool
}

// Module implements network protocol hardening checks.
type Module struct {
	ipv6DisablePath string
	modprobeDir     string
	hostsAllowPath  string
	hostsDenyPath   string
	wirelessPath    string
	passwdPath      string
}

func (m *Module) Name() string    { return "network" }
func (m *Module) Version() string { return "0.1.0" }

// Audit inspects network hardening settings and returns findings.
func (m *Module) Audit(_ context.Context, cfg modules.ModuleConfig) ([]modules.Finding, error) {
	findings := make([]modules.Finding, 0, 8)

	findings = append(findings, m.auditIPv6(cfg))

	for _, c := range moduleBlacklistChecks() {
		findings = append(findings, m.auditBlacklistedModule(c, cfg))
	}

	findings = append(findings, m.auditWireless(cfg))
	findings = append(findings, m.auditTCPWrappers())
	findings = append(findings, m.auditHomeSecrets())

	return findings, nil
}

// Plan writes a single modprobe blacklist file for non-compliant protocol modules.
func (m *Module) Plan(ctx context.Context, cfg modules.ModuleConfig) ([]modules.Change, error) {
	findings, err := m.Audit(ctx, cfg)
	if err != nil {
		return nil, err
	}

	checks := moduleBlacklistChecks()
	missing := make([]moduleCheck, 0, len(checks))
	for _, chk := range checks {
		if !cfgBool(cfg, chk.configKey, chk.defaultBool) {
			continue
		}
		if isFindingCompliant(findings, chk.id) {
			continue
		}
		missing = append(missing, chk)
	}
	if len(missing) == 0 {
		return nil, nil
	}

	path := filepath.Join(m.modprobeDirPath(), blacklistFileName)
	oldContent, readErr := os.ReadFile(path)
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, fmt.Errorf("network: read existing %s: %w", path, readErr)
	}
	existed := readErr == nil

	var sb strings.Builder
	sb.WriteString("# Generated by hardbox - network protocol blacklists\n")
	for _, chk := range missing {
		sb.WriteString(fmt.Sprintf("blacklist %s\n", chk.moduleName))
		sb.WriteString(fmt.Sprintf("install %s /bin/true\n", chk.moduleName))
	}
	newContent := []byte(sb.String())

	return []modules.Change{
		{
			Description:  fmt.Sprintf("network: write protocol blacklist config to %s", path),
			DryRunOutput: sb.String(),
			Apply: func() error {
				return util.AtomicWrite(path, newContent, 0o644)
			},
			Revert: func() error {
				if !existed {
					return os.Remove(path)
				}
				return util.AtomicWrite(path, oldContent, 0o644)
			},
		},
	}, nil
}

func (m *Module) auditIPv6(cfg modules.ModuleConfig) modules.Finding {
	chk := modules.Check{
		ID:       "net-001",
		Title:    "IPv6 disabled if not used",
		Severity: modules.SeverityMedium,
		Compliance: []modules.ComplianceRef{
			{Framework: "CIS", Control: "3.1.1"},
		},
	}

	disableIPv6 := cfgBool(cfg, "disable_ipv6", false)
	val, err := readTrimmed(m.ipv6Path())
	if err != nil {
		return modules.Finding{Check: chk, Status: modules.StatusError, Current: "unreadable", Target: "0 or 1", Detail: err.Error()}
	}

	if !disableIPv6 {
		return modules.Finding{Check: chk, Status: modules.StatusManual, Current: val, Target: "disabled when not used", Detail: "profile does not require disabling IPv6"}
	}
	return modules.Finding{Check: chk, Status: modules.ComplianceStatus(val == "1"), Current: val, Target: "1", Detail: "read net.ipv6.conf.all.disable_ipv6"}
}

func (m *Module) auditBlacklistedModule(c moduleCheck, cfg modules.ModuleConfig) modules.Finding {
	chk := modules.Check{
		ID:       c.id,
		Title:    c.title,
		Severity: c.severity,
		Compliance: []modules.ComplianceRef{
			{Framework: "CIS", Control: c.cisRef},
		},
	}

	if !cfgBool(cfg, c.configKey, c.defaultBool) {
		return modules.Finding{Check: chk, Status: modules.StatusSkipped, Current: "not enforced", Target: "blacklisted", Detail: fmt.Sprintf("config %q disabled", c.configKey)}
	}

	present, evidence := isModuleBlacklisted(m.modprobeDirPath(), c.moduleName)
	status := modules.StatusNonCompliant
	if present {
		status = modules.StatusCompliant
	}
	return modules.Finding{Check: chk, Status: status, Current: evidence, Target: "blacklist + install /bin/true", Detail: fmt.Sprintf("module %q", c.moduleName)}
}

func (m *Module) auditWireless(cfg modules.ModuleConfig) modules.Finding {
	chk := modules.Check{
		ID:       "net-006",
		Title:    "Wireless interfaces disabled",
		Severity: modules.SeverityMedium,
		Compliance: []modules.ComplianceRef{
			{Framework: "CIS", Control: "3.1.2"},
		},
	}

	if !cfgBool(cfg, "disable_wireless", true) {
		return modules.Finding{Check: chk, Status: modules.StatusSkipped, Current: "not enforced", Target: "disabled", Detail: "profile does not require disabling wireless"}
	}

	data, err := os.ReadFile(m.wirelessProcPath())
	if err != nil {
		if os.IsNotExist(err) {
			return modules.Finding{Check: chk, Status: modules.StatusCompliant, Current: "no /proc/net/wireless", Target: "no active wireless", Detail: "wireless subsystem not present"}
		}
		return modules.Finding{Check: chk, Status: modules.StatusError, Current: "unreadable", Target: "no active wireless", Detail: err.Error()}
	}

	lines := strings.Split(strings.TrimSpace(string(data)), "\n")
	if len(lines) <= 2 {
		return modules.Finding{Check: chk, Status: modules.StatusCompliant, Current: "0 interfaces", Target: "0 interfaces", Detail: "no wireless interfaces detected"}
	}
	ifaces := 0
	for _, line := range lines[2:] {
		if strings.TrimSpace(line) != "" {
			ifaces++
		}
	}
	return modules.Finding{Check: chk, Status: modules.ComplianceStatus(ifaces == 0), Current: fmt.Sprintf("%d interfaces", ifaces), Target: "0 interfaces", Detail: "parsed /proc/net/wireless"}
}

func (m *Module) auditTCPWrappers() modules.Finding {
	chk := modules.Check{
		ID:       "net-007",
		Title:    "hosts.allow / hosts.deny configured",
		Severity: modules.SeverityLow,
	}

	allow, allowErr := readTrimmed(m.hostsAllow())
	deny, denyErr := readTrimmed(m.hostsDeny())
	if allowErr != nil || denyErr != nil {
		return modules.Finding{Check: chk, Status: modules.StatusNonCompliant, Current: "missing files", Target: "both configured", Detail: "hosts.allow and hosts.deny must exist and be non-empty"}
	}
	ok := allow != "" && deny != ""
	return modules.Finding{Check: chk, Status: modules.ComplianceStatus(ok), Current: fmt.Sprintf("allow=%t deny=%t", allow != "", deny != ""), Target: "both non-empty", Detail: "basic TCP wrappers presence check"}
}

func (m *Module) auditHomeSecrets() modules.Finding {
	chk := modules.Check{
		ID:       "net-008",
		Title:    "No .rhosts / .netrc files in home dirs",
		Severity: modules.SeverityHigh,
	}

	homes, err := parseHomeDirs(m.passwdFile())
	if err != nil {
		return modules.Finding{Check: chk, Status: modules.StatusError, Current: "unreadable", Target: "none", Detail: err.Error()}
	}

	found := make([]string, 0)
	for _, home := range homes {
		for _, name := range []string{".rhosts", ".netrc"} {
			p := filepath.Join(home, name)
			if _, err := os.Stat(p); err == nil {
				found = append(found, p)
			}
		}
	}
	sort.Strings(found)
	if len(found) == 0 {
		return modules.Finding{Check: chk, Status: modules.StatusCompliant, Current: "none found", Target: "none", Detail: fmt.Sprintf("scanned %d home directories", len(homes))}
	}
	return modules.Finding{Check: chk, Status: modules.StatusNonCompliant, Current: strings.Join(found, ", "), Target: "none", Detail: "remove legacy trust files"}
}

func moduleBlacklistChecks() []moduleCheck {
	return []moduleCheck{
		{id: "net-002", title: "DCCP kernel module blacklisted", severity: modules.SeverityMedium, cisRef: "3.4.1", moduleName: "dccp", configKey: "disable_dccp", defaultBool: true},
		{id: "net-003", title: "SCTP kernel module blacklisted", severity: modules.SeverityMedium, cisRef: "3.4.2", moduleName: "sctp", configKey: "disable_sctp", defaultBool: true},
		{id: "net-004", title: "RDS kernel module blacklisted", severity: modules.SeverityMedium, cisRef: "3.4.3", moduleName: "rds", configKey: "disable_rds", defaultBool: true},
		{id: "net-005", title: "TIPC kernel module blacklisted", severity: modules.SeverityMedium, cisRef: "3.4.4", moduleName: "tipc", configKey: "disable_tipc", defaultBool: true},
	}
}

func isModuleBlacklisted(modprobeDir, moduleName string) (bool, string) {
	entries, err := os.ReadDir(modprobeDir)
	if err != nil {
		return false, "modprobe dir unreadable"
	}
	hasBlacklist := false
	hasInstall := false
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".conf") {
			continue
		}
		p := filepath.Join(modprobeDir, e.Name())
		lines := readLines(p)
		for _, raw := range lines {
			line := strings.TrimSpace(raw)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			fields := strings.Fields(line)
			if len(fields) >= 2 && fields[0] == "blacklist" && fields[1] == moduleName {
				hasBlacklist = true
			}
			if len(fields) >= 3 && fields[0] == "install" && fields[1] == moduleName && fields[2] == "/bin/true" {
				hasInstall = true
			}
		}
	}
	if hasBlacklist && hasInstall {
		return true, "blacklist+install present"
	}
	if hasBlacklist {
		return false, "missing install /bin/true"
	}
	if hasInstall {
		return false, "missing blacklist entry"
	}
	return false, "missing"
}

func parseHomeDirs(passwdPath string) ([]string, error) {
	f, err := os.Open(passwdPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	seen := make(map[string]struct{})
	homes := make([]string, 0)
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Split(line, ":")
		if len(parts) < 7 {
			continue
		}
		home := strings.TrimSpace(parts[5])
		if len(parts) > 7 {
			// Keep parser robust in test environments where temp paths may contain ':'.
			home = strings.TrimSpace(strings.Join(parts[5:len(parts)-1], ":"))
		}
		if home == "" || home == "/" {
			continue
		}
		if _, ok := seen[home]; ok {
			continue
		}
		seen[home] = struct{}{}
		homes = append(homes, home)
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	return homes, nil
}

func readTrimmed(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}

func readLines(path string) []string {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	return strings.Split(string(b), "\n")
}

func cfgBool(cfg modules.ModuleConfig, key string, fallback bool) bool {
	if cfg != nil {
		if v, ok := cfg[key]; ok {
			if b, ok := v.(bool); ok {
				return b
			}
		}
	}
	return fallback
}

func isFindingCompliant(findings []modules.Finding, checkID string) bool {
	for _, f := range findings {
		if f.Check.ID == checkID {
			return f.IsCompliant()
		}
	}
	return false
}

func (m *Module) ipv6Path() string {
	if m.ipv6DisablePath != "" {
		return m.ipv6DisablePath
	}
	return defaultIPv6DisablePath
}

func (m *Module) modprobeDirPath() string {
	if m.modprobeDir != "" {
		return m.modprobeDir
	}
	return defaultModprobeDir
}

func (m *Module) hostsAllow() string {
	if m.hostsAllowPath != "" {
		return m.hostsAllowPath
	}
	return defaultHostsAllowPath
}

func (m *Module) hostsDeny() string {
	if m.hostsDenyPath != "" {
		return m.hostsDenyPath
	}
	return defaultHostsDenyPath
}

func (m *Module) wirelessProcPath() string {
	if m.wirelessPath != "" {
		return m.wirelessPath
	}
	return defaultWirelessPath
}

func (m *Module) passwdFile() string {
	if m.passwdPath != "" {
		return m.passwdPath
	}
	return defaultPasswdPath
}
